baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'HUGOTEST'

[permalinks]
  posts = "/blog/:year/:month/:day/:slug/"
  years  = "/blog/:slug/"
  months = "/blog/:slug/"
  days   = "/blog/:slug/"

[taxonomies]
  category = 'categories'
  tag = 'tags'
  year = "years"
  month = "months"
  day = "days"