backend:
  name: git-gateway
  repo: nomisK1/hugotest
  branch: master
  commit_messages:
    create: "Post: Create {{collection}} {{slug}}"
    update: "Post: Update {{collection}} {{slug}}"
    delete: "Post: Delete {{collection}} {{slug}}"
    uploadMedia: "Media: Upload {{path}}"
    deleteMedia: "Media: Delete {{path}}"
    openAuthoring: "{{message}}"

site_url: https://hugotestin.netlify.app/
display_url: https://hugotestin.netlify.app/

media_folder: static/media
public_folder: /media

logo_url: /svg/logo.svg
publish_mode: simple

collections:
  - name: blog
    label: Blog
    label_singular: Post
    folder: content/blog
    create: true
    slug: "{{slug}}"
    path: "{{year}}/{{month}}/{{day}}/{{slug}}/index"
    filter: { field: layout, value: single }
    fields:
      - { label: Title, name: title, widget: string }
      - { label: Type, name: type, default: blog, hidden: true }
      - { label: Layout, name: layout, default: single, hidden: true }
      - { label: Date, name: date, widget: datetime, default: "{{now}}" }
      - {
          label: Year,
          name: years,
          widget: datetime,
          default: "{{year}}",
          hidden: false,
        }
      - {
          label: Month,
          name: months,
          widget: datetime,
          default: "{{month}}",
          hidden: false,
        }
      - {
          label: Day,
          name: days,
          widget: datetime,
          default: "{{day}}",
          hidden: false,
        }
      - { label: Draft, name: draft, widget: boolean, default: true }
      - {
          label: Author,
          name: author,
          widget: string,
          default,
          required: false,
        }
      - {
          label: Description,
          name: description,
          widget: string,
          default,
          required: false,
        }
      - { label: Categories, name: categories, widget: list, default: [] }
      - { label: Tags, name: tags, widget: list, default: [] }
      - { label: Body, name: body, widget: markdown }
      - {
          label: Featured Image,
          name: thumbnail,
          widget: image,
          max_file_size: 5242880,
          required: false,
        }
