backend:
  name: git-gateway
  repo: nomisK1/hugotest
  branch: master
  base_url: https://api.netlify.com

site_url: https://www.blauerzettel.de
display_url: https://blauerzettel.de

media_folder: static/media
public_folder: /media

collections:
  - name: "blog"
    label: "Blog"
    label_singular: "Post"
    folder: "content/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    path: "{{year}}/{{slug}}"
    filter: { field: "type", value: "post" }
    fields:
      - { label: "Title", name: "title", widget: "string", default: "{{slug}}" }
      - {
          label: "Description",
          name: "description",
          widget: "string",
          default: "...",
        }
      - { label: "Publish Date", name: "date", widget: "datetime", default: "{{now}}" }
      - { label: "Draft", name: "draft", widget: "boolean", default: true }
      - { label: "Author", name: "author", widget: "string", default: "anonymous" }
      - { label: "Tags", name: "tags", widget: "list", default: ["new"] }
      - { label: "Categories", name: "categories", widget: "list", default: ["general"] }
      - { label: "Type", name: "type", widget: "hidden", default: "post" }
      - { label: "Layout", name: "layout", widget: "hidden", default: "single" }
      - { label: "Body", name: "body", widget: "markdown", default: "..." }